name: Update Browserslist database

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-browserslist-database:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        run: npm ci
      - name: Update Browserslist database (old way)
        run: npx browserslist@latest --update-db
      - name: Create PR
        run: gh pr create --title "Update browserslist database" --label "ci" --body "test"
